version: 2.1

jobs:
  build:
    docker:
      - image: misterabdul/c-build-environment:0.0.1
    steps:
      - checkout
      - run: |
          git submodule update --init --recursive
          ./configure
          mkdir -p build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr ..
          make
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: misterabdul/c-build-environment:0.0.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          cd build
          sudo make install
          sudo ldconfig
          mkdir -p /tmp/artifacts/test
          cd test && make
          ./test > /tmp/artifacts/test/test_result.txt || true
          valgrind --tool=memcheck --leak-check=full -s --log-file=/tmp/artifacts/test/valgrind_result.txt test || true
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
