version: 2.1

jobs:
  build:
    docker:
      - image: misterabdul/c-build-environment:0.0.1
    steps:
      - checkout
      - run: pwd
      - run: git submodule update --init --recursive
      - run: ./cpdeps.sh
      - run: mkdir -p build && cd build
      - run: ls
      - run: pwd
      - run: cmake ..
      - run: make && make install
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: misterabdul/c-build-environment:0.0.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: make install && make test && ./test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
