version: 2.1

jobs:
  build:
    docker:
      - image: fedora:34
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: ./cpdeps.sh
      - run: mkdir -p build && cd build
      - run: cmake ..
      - run: make && make install
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: fedora:34
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: make install && make test && ./test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
