version: 2.1

jobs:
  build:
    docker:
      - image: misterabdul/c-build-environment:0.0.1
    steps:
      - checkout
      - run: |
          git submodule update --init --recursive
          ./cpdeps.sh
          mkdir -p build
          cd build
          cmake ..
          make
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: misterabdul/c-build-environment:0.0.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          cd build
          make install
          make test
          ./test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
